baseURL = 'https://steblik.com/'
languageCode = 'en-us'
title = 'Miroslaw Steblik'
theme = 'steblik'

[params]
  bannerImage = '/images/banner_pipeline.jpeg'
  mainSections = ["posts"]
  postsPerPage = 6 # Controls how many posts are displayed per page
  
[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 10

  [[menus.main]]
    name = 'About'
    url = '/about/'
    weight = 20

  [[menus.main]]
    name = 'Data Engineering Blog'
    url = '/posts/'
    weight = 30

  [[menus.social]]
    name = 'GitHub'
    url = 'https://github.com/miroslawsteblik'
    weight = 10
    
  [[menus.social]]
    name = 'LinkedIn'
    url = 'https://linkedin.com/in/miroslawsteblik'
    weight = 20

  [[menus.social]]
    name = 'Email'
    url = 'mailto:your.email@example.com'
    weight = 30

