baseURL = 'https://steblik.com/'
languageCode = 'en-us'
title = 'Miroslaw Steblik'

[module]
  [[module.imports]]
    path = "github.com/miroslawsteblik/hugo-theme-data-blog"
    version = "main"

[params]
  bannerImage = '/images/banner_pipeline.jpeg'
  postsPerPage = 6 # Controls how many posts are displayed per page

[params.social]
  github = "miroslawsteblik"
  linkedin = "miroslawsteblik"
  email = "data@steblik.com"

[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 10

  [[menus.main]]
    name = 'About'
    url = '/about/'
    weight = 20

  [[menus.main]]
    name = 'Data Engineering Blog'
    url = '/posts/'
    weight = 30

